name: talent_find
description: "TalentTrack - Sports Authority of India Talent Assessment Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Fonts
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8

  # Firebase Core (required for all Firebase services)
  firebase_core: ^3.6.0
  provider: ^6.1.2
  http: ^1.2.2  # For API calls
  url_launcher: ^6.3.1

  # Firebase Authentication
  firebase_auth: ^5.3.1

  # Cloud Firestore (for database)
  cloud_firestore: ^5.4.3

  # Google Sign In (compatible with firebase_auth 5.3.1)
  google_sign_in: ^6.2.1

  # Video and Camera functionality
  camera: ^0.10.5+5

  # File handling
  path: ^1.8.3

  # Image processing (for video frame extraction)
  image: ^4.0.17

  # Permissions
  permission_handler: ^11.0.1

  crypto: ^3.0.3


  dio: ^5.3.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  # File operations
  file_picker: ^8.0.7
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets - Your TFLite model
  assets:
    - assets/models/

